### ISSUE TITLE
Google Assistant voice control?

### ISSUE THREAD

**Issue by Hukuma1** [jaruba/ha-samsungtv-custom#14]
Hi! Thanks for taking the time with this component. I'm currently looking at a way to control the TV with Home Assistant -> Google Assistant. I noticed the component says you can use your voice. What is the proper workflow here?

I currently have your component loaded in HA and can issue commands via clicking. How do I add it into Google Home/Google Assistant? Samsung says if you link it to SmartThings and then set it up via that, it adds the TV. Unfortunately, for some reason Google Home only sees my TV as a light switch. On/Off is all I can control at that point, and it can't even turn it on I believe. Using the SmartThings app works with ease as expected. But I really want to add Google Assistant to be able to control the TV along with my lights in a scene, etc. Is this not possible yet?

**Comment by jaruba** [comment]
Have you setup your Google Assistant in Home Assistant yet?
https://www.home-assistant.io/integrations/google_assistant/

If yes, then sync your devices. If no, then set it up.

**Comment by Hukuma1** [comment]
Ah I see. I had to issue sync command to Google after adding new device. Seems to be showing up now, will do more testing of the abilities. Thank you!

**Comment by jaruba** [comment]
It happened to me a few times after syncing that it wouldn't support all voice features mentioned in the readme. If that happens to u too, and ur google home says it's not understanding the command, then sync your devices (yet again), that fixed it for my tests.

**Comment by Hukuma1** [comment]
There seems to be a delay from when you turn off TV and when you can turn it back on? Had to issue voice command twice to turn it back on. But can live with this for now.

Is there a way to get this component also into Apple Home for Siri commands? I’m trying to link all assistants together haha.

**Comment by jaruba** [comment]
@Hukuma1 There is indeed a delay between turning off and turning back on, there is a similar delay when turning it on and back off again. This comes from the Samsung TVs themselves, there's nothing we can do about that for now.

It should work with Siri too, in a similar way, I can't tell you the process though as I don't have any Alexa device. But from what I heard, Alexa supports a lot less commands then Google Assistant. It might show up only as a light bulb with Alexa devices.
